import psycopg2
from db_config import config

config_data = config()


class PostgresSQLConnection:

    def __init__(self, dbname=config_data['database']):
        self.dbname = dbname
        self.user = config_data['user']
        self.password = config_data['password']
        self.host = config_data['host']
        self.port = config_data['port']
        self.connection = None
        self.create_db_tables()

    def connect_with_db(self):
        self.connection = psycopg2.connect(
            dbname=self.dbname,
            user=self.user,
            password=self.password,
            host=self.host,
            port=self.port)

    def execute_query(self, query, params=None):
        if not self.connection:
            self.connect_with_db()
        self.connection.autocommit = False
        cursor = self.connection.cursor()
        cursor.execute(query, params)
        try:
            fetched_data = cursor.fetchall()
        except psycopg2.ProgrammingError:
            return None
        else:
            return fetched_data
        finally:
            cursor.close()

    def close_connection_with_db(self):
        if self.connection:
            self.connection.close()
            self.connection = None

    def database_transaction(self, query, params=None):
        try:
            self.connect_with_db()
            fetched_data = self.execute_query(query, params)
        except (Exception, psycopg2.DatabaseError) as error:
            print("Error in transaction. Reverting all other operations of a transaction ", error)
            self.connection.rollback()
            return False
        else:
            self.connection.commit()
            return fetched_data
        finally:
            self.close_connection_with_db()

    def create_db_tables(self):
        self.database_transaction(query="""CREATE TABLE IF NOT EXISTS server_versions (
                                                                        version VARCHAR(20) PRIMARY KEY,
                                                                        version_date TIMESTAMP);""")
        self.database_transaction(query="""CREATE TABLE IF NOT EXISTS users (
                                                                    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
                                                                    username VARCHAR PRIMARY KEY);""")
        self.database_transaction(query="""CREATE TABLE IF NOT EXISTS users_privileges (
                                    username VARCHAR PRIMARY KEY,
                                    privileges VARCHAR NOT NULL DEFAULT user,
                                    FOREIGN KEY (username) REFERENCES users(username) ON DELETE CASCADE);""")
        self.database_transaction(query="""CREATE TABLE IF NOT EXISTS users_passwords (
                                    username VARCHAR PRIMARY KEY,
                                    password VARCHAR NOT NULL,
                                    FOREIGN KEY (username) REFERENCES users(username) ON DELETE CASCADE);""")
        self.database_transaction(query="""CREATE TABLE IF NOT EXISTS users_messages (
                                message_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
                                sender_username VARCHAR NOT NULL,
                                recipient_username VARCHAR NOT NULL,
                                message_content VARCHAR(255) NOT NULL,
                                sending_date TIMESTAMP NOT NULL,
                                read_by_recipient BOOLEAN DEFAULT false NOT NULL,
                                FOREIGN KEY (sender_username) REFERENCES users(username) ON DELETE CASCADE,
                                FOREIGN KEY (recipient_username) REFERENCES users(username) ON DELETE CASCADE);""")

        self.database_transaction(query="""CREATE TABLE IF NOT EXISTS admin_tokens (
                                                                        token_id VARCHAR PRIMARY KEY,
                                                                        is_valid BOOLEAN NOT NULL DEFAULT TRUE);""")